application: haoyu-experiment
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# - url: /.*
#   script: controllers.main.app
#   secure: always

# - url: /
#   static_files: index.html
#   upload: index.html

- url: /
  script: main.app
  secure: always
- url: /newpage
  script: main.app
  secure: always



# access the static resources in the root director
# - url: /(.*)
#   static_files: \1
#   upload: (.*)
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


# access the static resources in the root director
# - url: /(.*)
#   static_files: \1
#   upload: (.*)

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"